version: "3.0"
services:
  db:
    image: "postgres:13.1-alpine"
    container_name: db
    ports:
      - "46077:5432"
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
      - POSTGRES_DB=assembly-voting-manager-db
    networks:
      - mynet
  app:
    build: .
    restart: always
    expose:
      - 8080
    ports:
      - "8080:8080"
    container_name: app
    networks:
      - mynet

networks:
  mynet:
    driver: bridge